Repository movementlabsxyz/MIP, pull requests merged in 2025-01, with the labels that each got.

#79 Fix Grammar and Terminology Consistency in Documentation
  README.md
Labels: Typos/minor fixes

#78 [update] MDbook: add mathjax, katex, fix testing links, and much more
  .github/workflows/mipbook.yml
  generate_book.sh
  get_auth_token.sh
Labels: MDBook

#83 [update] MIP-39: fix link texts
  MIP/mip-39/README.md
Labels: ready-to-merge

#45 [update] definition of glossary and MG
  GLOSSARY.md
  MG/mg-0/README.md
  MIP/mip-15/README.md
  README.md
  mg-template.md
Labels: Urgent

#88 [review] MIP-88: Lock-Mint Bridge Rate Limiter: Simplified design
  .github/CODEOWNERS
  MIP/mip-88/README.md
  MIP/mip-88/overview.png
  MIP/mip-88/overview2.png
Labels: bridge, Draft MD/MIP, Ready to Review, MIP, Committee review
